# Generated by Django 4.0.4 on 2022-05-22 13:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0003_alter_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyVisits',
            new_name='DailyVisit',
        ),
        migrations.RenameModel(
            old_name='ProductViews',
            new_name='ProductView',
        ),
    ]
