# Generated by Django 4.0.4 on 2022-05-23 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='extr_images',
        ),
        migrations.AddField(
            model_name='extraproductimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='backend.product'),
        ),
    ]
