# Generated by Django 4.0.4 on 2022-05-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_merchant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='uploads/images/banners/')),
                ('link', models.URLField(blank=True, default='', null=True)),
                ('published', models.BooleanField(default=True)),
                ('product_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'banners',
            },
        ),
    ]
