# Generated by Django 4.0.4 on 2022-05-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
