# Generated by Django 4.0.4 on 2022-05-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.CharField(default='Ghana', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='facebook',
            field=models.URLField(default='https://www.facebook.com/'),
        ),
        migrations.AddField(
            model_name='account',
            name='instagram',
            field=models.URLField(default='https://www.instagram.com/'),
        ),
        migrations.AddField(
            model_name='account',
            name='linkedIn',
            field=models.URLField(default='https://www.linkedin.com/'),
        ),
        migrations.AddField(
            model_name='account',
            name='twitter',
            field=models.URLField(default='https/www.twitter.com/'),
        ),
    ]
